on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: git pull and build
      run: |
        cd /home/user/candle-constructor
        git pull origin main
        npm install
        npx prisma generate
        npm run build 
        npx prisma migrate deploy
        pm2 restart website
      shell: bash
